 artifacts_root : artifacts

 Data_Ingestion:
  root_dir : artifacts/DataIngestion 
  oracledbconnection :
    host : localhost
    port : 1521
    service : free
    username : SYSTEM
    password : sys
  source_table : COM_LOG
  local_data_file : artifacts/DataIngestion/com_data_log.csv

 
 Data_Cleaning :
  root_dir : artifacts/Data_Cleaning
  source_path : artifacts/DataIngestion/com_data_log.csv
  local_data_file : artifacts/DataIngestion/pre_processed_log.csv
   