 artifacts_root : artifacts

 Data_Ingestion:
  root_dir : artifacts/DataIngestion 
  oracledbconnection :
    host : localhost
    port : 1521
    service : free
    username : SYSTEM
    password : rsr
  source_table : COM_LOG
  local_data_file : artifacts/DataIngestion/com_data_log.csv

 
 Data_Cleaning :
  root_dir : artifacts/Data_Cleaning
  source_path : artifacts/DataIngestion/com_data_log.csv
  local_data_file : artifacts/Data_Cleaning/pre_processed_log.csv

 Create_Embendings :
  root_dir : artifacts/Create_Embendings
  source_path : artifacts/Data_Cleaning/pre_processed_log.csv
  local_data_file : artifacts/Create_Embendings/embeddings.npy

 Create_Vectors :
  root_dir : artifacts/Create_Vectors
  faiss_index : artifacts/Create_Vectors/faiss_index
  source_path : artifacts/DataIngestion/com_data_log.csv
  local_data_file : artifacts/Create_Vectors/index.pkl
 Create_Rag_Engine :
  root_dir : artifacts/Rag_Engine
  faiss_index : artifacts/Create_Vectors/faiss_index
  source_path : artifacts/Create_Vectors/index.pkl
  local_data_file : artifacts/Rag_Engine/index.pkl

   